FROM pandoc/latex

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

RUN tlmgr update --self
RUN tlmgr install verbatimbox
RUN tlmgr install readarray
RUN tlmgr install forloop
RUN tlmgr install listofitems
RUN tlmgr install lato
RUN tlmgr install fontaxes
RUN tlmgr install xkeyval
RUN tlmgr install lipsum
RUN tlmgr install microtype
RUN tlmgr install moresize
RUN tlmgr install amsmath
RUN tlmgr install changepage
RUN tlmgr install menukeys
RUN tlmgr install xstring
RUN tlmgr install adjustbox
RUN tlmgr install relsize
RUN tlmgr install newfloat
RUN tlmgr install titlesec
RUN tlmgr install eso-pic
RUN tlmgr install tcolorbox
RUN tlmgr install wrapfig
RUN tlmgr install footmisc
RUN tlmgr install hyperref
RUN tlmgr install enumitem
RUN tlmgr install biblatex-abnt
RUN tlmgr install biblatex-apa
RUN tlmgr install xpatch
RUN tlmgr install cmap
RUN tlmgr install fontsize
RUN tlmgr install usebib
RUN tlmgr install ctable
RUN tlmgr install beamer
RUN tlmgr install beamertheme-metropolis
RUN tlmgr install pgfopts
RUN tlmgr install listingsutf8
RUN tlmgr install doublestroke
RUN tlmgr install cellspace
RUN tlmgr install realboxes
RUN tlmgr install tikzfill
RUN tlmgr install pdfcol
